In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pt
import seaborn as sns
get_ipython().run_line_magic('matplotlib', 'inline')

In [2]:
data= pd.read_csv('C:\\Users\\Vinayaka\\Desktop\\p32\\df8.csv',engine="python",na_values=" ")

In [ ]:
data

In [3]:
data.min()

loan_amnt                         500.00
terms                              36.00
Rate_of_intrst                      5.32
grade                               1.00
Experience                          0.00
annual_inc                       1896.00
verification_status                 1.00
debt_income_ratio                   0.00
numb_credit                         0.00
total revol_bal                     0.00
total_credits                       0.00
total_rec_int                       0.00
last_week_pay                       0.00
tot_curr_bal                        0.00
MORTGAGE                            0.00
OWN                                 0.00
RENT                                0.00
Cars and Major purchases            0.00
House and house imporovements       0.00
Wedding and Vacation                0.00
credit_card                         0.00
debt_consolidation                  0.00
medical                             0.00
small_business                      0.00
f                                   0.00
dtype: float64

In [4]:
data.max()

loan_amnt                         29000.0
terms                                60.0
Rate_of_intrst                       23.0
grade                                 7.0
Experience                           10.0
annual_inc                       125000.0
verification_status                   3.0
debt_income_ratio                    40.0
numb_credit                          22.0
total revol_bal                   28000.0
total_credits                        48.0
total_rec_int                      3700.0
last_week_pay                       160.0
tot_curr_bal                     300000.0
MORTGAGE                              1.0
OWN                                   1.0
RENT                                  1.0
Cars and Major purchases              1.0
House and house imporovements         1.0
Wedding and Vacation                  1.0
credit_card                           1.0
debt_consolidation                    1.0
medical                               1.0
small_business                        1.0
f                                     1.0
dtype: float64

In [5]:
from sklearn.preprocessing import MinMaxScaler

In [6]:
scaler = MinMaxScaler()
df_s = scaler.fit_transform(data)

In [7]:
df_s=pd.DataFrame(df_s)
df_s

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,0.485965,0.0,0.784502,0.333333,0.9,0.217735,1.0,0.8470,0.636364,0.804107,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,0.150877,0.0,0.320701,0.833333,0.0,0.512607,1.0,0.0910,0.272727,0.272286,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.333333,0.0,0.109729,1.000000,0.2,0.350143,0.0,0.4605,0.227273,0.388464,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.157895,0.0,0.145928,1.000000,0.5,0.593839,1.0,0.1425,0.590909,0.474000,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,0.508772,0.0,0.744910,0.500000,0.4,0.601963,0.5,0.3965,0.681818,0.503036,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615016,0.763158,0.0,0.145928,1.000000,0.5,0.683195,0.5,0.7125,0.636364,0.960607,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
615017,0.484211,0.0,0.570701,0.500000,1.0,0.407005,0.5,0.4825,0.681818,0.345964,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
615018,0.508772,0.0,0.066176,1.000000,0.1,0.774581,0.0,0.3115,0.545455,0.435750,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
615019,0.473684,1.0,0.689480,0.333333,1.0,0.439498,0.5,0.4110,0.500000,0.391000,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
615020,0.077193,1.0,0.122738,1.000000,0.2,0.082077,0.0,0.7000,0.318182,0.182786,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [8]:
column= data.columns
column

Index(['loan_amnt', 'terms', 'Rate_of_intrst', 'grade', 'Experience',
       'annual_inc', 'verification_status', 'debt_income_ratio', 'numb_credit',
       'total revol_bal', 'total_credits', 'total_rec_int', 'last_week_pay',
       'tot_curr_bal', 'MORTGAGE', 'OWN', 'RENT', 'Cars and Major purchases',
       'House and house imporovements', 'Wedding and Vacation', 'credit_card',
       'debt_consolidation', 'medical', 'small_business', 'f'],
      dtype='object')

In [9]:
df_s.columns =['loanamnt', 'terms','Rateofintrst', 'grade', 'Experience',
       'annualinc', 'verificationstatus', 'debtincomeratio', 'numbcredit',
       'totalrevolbal', 'totalcredits', 'totalrecint', 'lastweekpay',
       'totcurrbal', 'MORTGAGE', 'OWN', 'RENT', 'CarsMajorpurchases',
       'Househouseimporovements', 'WeddingVacation', 'creditcard',
       'debtconsolidation', 'medical', 'smallbusiness', 'f']

In [10]:
df_s

,loanamnt,terms,Rateofintrst,grade,Experience,annualinc,verificationstatus,debtincomeratio,numbcredit,totalrevolbal,...,OWN,RENT,CarsMajorpurchases,Househouseimporovements,WeddingVacation,creditcard,debtconsolidation,medical,smallbusiness,f
0,0.485965,0.0,0.784502,0.333333,0.9,0.217735,1.0,0.8470,0.636364,0.804107,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,0.150877,0.0,0.320701,0.833333,0.0,0.512607,1.0,0.0910,0.272727,0.272286,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.333333,0.0,0.109729,1.000000,0.2,0.350143,0.0,0.4605,0.227273,0.388464,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.157895,0.0,0.145928,1.000000,0.5,0.593839,1.0,0.1425,0.590909,0.474000,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,0.508772,0.0,0.744910,0.500000,0.4,0.601963,0.5,0.3965,0.681818,0.503036,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615016,0.763158,0.0,0.145928,1.000000,0.5,0.683195,0.5,0.7125,0.636364,0.960607,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
615017,0.484211,0.0,0.570701,0.500000,1.0,0.407005,0.5,0.4825,0.681818,0.345964,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
615018,0.508772,0.0,0.066176,1.000000,0.1,0.774581,0.0,0.3115,0.545455,0.435750,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
615019,0.473684,1.0,0.689480,0.333333,1.0,0.439498,0.5,0.4110,0.500000,0.391000,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
615020,0.077193,1.0,0.122738,1.000000,0.2,0.082077,0.0,0.7000,0.318182,0.182786,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [12]:
a = df_s['totalrevolbal']
df_s.drop(labels=['totalrevolbal'], axis=1,inplace = True)
df_s.insert(24, 'totalrevolbal', a)

In [13]:
df_s.head()

,loanamnt,terms,Rateofintrst,grade,Experience,annualinc,verificationstatus,debtincomeratio,numbcredit,totalcredits,...,RENT,CarsMajorpurchases,Househouseimporovements,WeddingVacation,creditcard,debtconsolidation,medical,smallbusiness,f,totalrevolbal
0,0.485965,0.0,0.784502,0.333333,0.9,0.217735,1.0,0.8470,0.636364,0.583333,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.804107
1,0.150877,0.0,0.320701,0.833333,0.0,0.512607,1.0,0.0910,0.272727,0.270833,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.272286
2,0.333333,0.0,0.109729,1.000000,0.2,0.350143,0.0,0.4605,0.227273,0.395833,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.388464
3,0.157895,0.0,0.145928,1.000000,0.5,0.593839,1.0,0.1425,0.590909,0.479167,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.474000
4,0.508772,0.0,0.744910,0.500000,0.4,0.601963,0.5,0.3965,0.681818,0.625000,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.503036

In [14]:
list(df_s)

['loanamnt',
 'terms',
 'Rateofintrst',
 'grade',
 'Experience',
 'annualinc',
 'verificationstatus',
 'debtincomeratio',
 'numbcredit',
 'totalcredits',
 'totalrecint',
 'lastweekpay',
 'totcurrbal',
 'MORTGAGE',
 'OWN',
 'RENT',
 'CarsMajorpurchases',
 'Househouseimporovements',
 'WeddingVacation',
 'creditcard',
 'debtconsolidation',
 'medical',
 'smallbusiness',
 'f',
 'totalrevolbal']

In [15]:
from sklearn.model_selection import train_test_split
df_train,df_test  = train_test_split(df_s,test_size = 0.2,random_state=0) # 20% size

In [16]:
df_train.head()

,loanamnt,terms,Rateofintrst,grade,Experience,annualinc,verificationstatus,debtincomeratio,numbcredit,totalcredits,...,RENT,CarsMajorpurchases,Househouseimporovements,WeddingVacation,creditcard,debtconsolidation,medical,smallbusiness,f,totalrevolbal
553406,0.228070,0.0,0.273190,0.833333,0.6,0.383936,0.0,0.63425,0.681818,0.458333,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.311500
495997,0.277193,0.0,0.359163,0.833333,0.7,0.471991,0.0,0.40900,0.681818,0.375000,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.391750
457070,0.077193,0.0,0.999434,0.166667,0.0,0.137152,0.5,0.76525,0.318182,0.208333,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.014929
600021,0.508772,0.0,0.394231,0.666667,0.9,0.374513,0.5,0.04500,0.272727,0.250000,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.401536
349214,0.684211,0.0,0.320701,0.833333,0.1,0.675071,1.0,0.30425,0.227273,0.229167,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.265500

In [30]:
X_train=df_train.iloc[:,0:24]
y_train=df_train.loc[:,["totalrevolbal"]]

X_test=df_test.iloc[:,0:24]
y_test=df_test.loc[:,["totalrevolbal"]]

In [31]:
import statsmodels.api as sm
model = sm.OLS(y_train, X_train).fit()
print(model.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:          totalrevolbal   R-squared (uncentered):                   0.804
Model:                            OLS   Adj. R-squared (uncentered):              0.804
Method:                 Least Squares   F-statistic:                          8.389e+04
Date:                Sat, 03 Oct 2020   Prob (F-statistic):                        0.00
Time:                        01:57:10   Log-Likelihood:                          81158.
No. Observations:              492016   AIC:                                 -1.623e+05
Df Residuals:                  491992   BIC:                                 -1.620e+05
Df Model:                          24
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
loanamnt                    0.3603      0.002    173.762      0.000       0.356       0.364
terms                      -0.0086      0.001    -10.116      0.000      -0.010      -0.007
Rateofintrst                0.0164      0.004      3.822      0.000       0.008       0.025
grade                       0.0841      0.005     17.871      0.000       0.075       0.093
Experience                  0.0239      0.001     30.041      0.000       0.022       0.025
annualinc                   0.1818      0.002     97.325      0.000       0.178       0.185
verificationstatus         -0.0113      0.001    -15.844      0.000      -0.013      -0.010
debtincomeratio             0.2614      0.002    161.450      0.000       0.258       0.265
numbcredit                  0.2533      0.002    123.186      0.000       0.249       0.257
totalcredits               -0.0951      0.002    -48.195      0.000      -0.099      -0.091
totalrecint                 0.0126      0.002      5.883      0.000       0.008       0.017
lastweekpay                 0.0516      0.002     27.249      0.000       0.048       0.055
totcurrbal                  0.0557      0.001     38.816      0.000       0.053       0.059
MORTGAGE                   -0.1620      0.005    -30.372      0.000      -0.173      -0.152
OWN                        -0.1591      0.005    -29.664      0.000      -0.170      -0.149
RENT                       -0.1708      0.005    -32.226      0.000      -0.181      -0.160
CarsMajorpurchases         -0.0378      0.002    -18.465      0.000      -0.042      -0.034
Househouseimporovements    -0.0503      0.002    -29.325      0.000      -0.054      -0.047
WeddingVacation             0.0042      0.003      1.278      0.201      -0.002       0.011
creditcard                  0.0778      0.001     54.337      0.000       0.075       0.081
debtconsolidation           0.0148      0.001     11.074      0.000       0.012       0.017
medical                     0.0128      0.003      4.117      0.000       0.007       0.019
smallbusiness              -0.0411      0.003    -12.953      0.000      -0.047      -0.035
f                           0.0024      0.001      3.771      0.000       0.001       0.004
==============================================================================
Omnibus:                    22613.191   Durbin-Watson:                   2.001
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            26369.910
Skew:                           0.525   Prob(JB):                         0.00
Kurtosis:                       3.430   Cond. No.                         73.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [32]:
train_pred = model.predict(X_train)
train_resid = train_pred - y_train["totalrevolbal"]

In [33]:
train_rmse = np.sqrt(np.mean(train_resid*train_resid))
train_rmse

0.20517564904947924

In [34]:
test_pred2 = model.predict(X_test)

In [35]:
test_resid2  = test_pred2 - y_test["totalrevolbal"]

In [36]:
test_rmse2 = np.sqrt(np.mean(test_resid2*test_resid2))
test_rmse2

0.20540031279561943

In [37]:
test_pred2 = model.predict(X_test)

In [38]:
test_resid2  = test_pred2 - y_test["totalrevolbal"]

In [39]:
test_rmse2 = np.sqrt(np.mean(test_resid2*test_resid2))
test_rmse2

0.20540031279561943

In [40]:
pd.to_pickle(model,'1model.pickle')